version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 1
build_script:
- ps: >-
    dotnet build

    dotnet publish TestForAppveyor/ -c Release

    dotnet pack TestForAppveyor/ -c Release
artifacts:
- path: '**\*.nupkg'